---
apiVersion: v1
kind: Namespace
metadata:
  name: featurz-ns
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: featurz-config-map
  namespace: featurz-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: featurz
  namespace: featurz-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: featurz
  template:
    metadata:
      labels:
        app: featurz
    spec:
      containers:
        - name: featurz
          image: app/featurz:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 12345
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: featurz-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: featurz
  namespace: featurz-ns
spec:
  selector:
    app: featurz
  ports:
    - port: 50001
      targetPort: 12345
  type: LoadBalancer